"""Generate per-command adapter files (commands/<process>/<command>.md and .toml)."""

from __future__ import annotations

from typing import Any

from .context import GeneratorContext


def command_md(ctx: GeneratorContext, lane: dict[str, Any], skill_id: str) -> str:
    purpose = (lane.get("purpose") or lane.get("label") or skill_id).strip()
    return (
        f"# /{ctx.process_id}:{lane['id']}\n\n"
        f"**Skill:** `{skill_id}`  \n"
        f"**Purpose:** {purpose}\n\n"
        f"Run this command to invoke the `{skill_id}` skill for the {ctx.process_name} process. The skill follows the rules, state loop, and stop conditions defined by the GAPS v1 spec.\n\n"
        f"_Generated by gaps-v1-generator. Do not edit by hand._\n"
    )


def command_toml(ctx: GeneratorContext, lane: dict[str, Any], skill_id: str) -> str:
    return (
        f"# Generated by gaps-v1-generator. Do not edit by hand.\n"
        f"name = \"/{ctx.process_id}:{lane['id']}\"\n"
        f"skill = \"{skill_id}\"\n"
        f"path = \"skills/{skill_id}\"\n"
    )


def agents_openai_yaml(ctx: GeneratorContext, lane: dict[str, Any], skill_id: str) -> str:
    return (
        f"# Generated by gaps-v1-generator.\n"
        f"name: {skill_id}\n"
        f"description: >\n"
        f"  GAPS-generated skill for the {lane.get('label', lane['id'])} lane of the\n"
        f"  {ctx.process_name} process.\n"
        f"command: /{ctx.process_id}:{lane['id']}\n"
    )
