"""Compose SKILL.md content for each lane from a generative-conformance spec."""

from __future__ import annotations

from typing import Any

from .context import GeneratorContext
from .markdown import bullet_list, table


_NON_CLAIM = """## Non-claim language

This skill is a generated artifact of a GAPS v1 process specification. It does not by itself constitute regulatory compliance, certification, legal sufficiency, or runtime execution. The spec is the source of truth; do not edit this file by hand — regenerate from the spec instead.
"""


def _skill_id(process_id: str, lane_id: str) -> str:
    return f"{process_id}-{lane_id.replace('_', '-')}"


def _front_matter(process_id: str, lane: dict[str, Any], skill_id: str) -> str:
    description = lane.get("purpose", "").strip().splitlines()
    description_line = description[0] if description else lane.get("label", "")
    return (
        "---\n"
        f"name: {skill_id}\n"
        f"description: {description_line}\n"
        f"process: {process_id}\n"
        f"lane: {lane['id']}\n"
        "generatedBy: gaps-v1-generator\n"
        "doNotEditByHand: true\n"
        "---\n"
    )


def _input_quality_gate(ctx: GeneratorContext, lane: dict[str, Any]) -> str:
    rows: list[list[str]] = []
    for ev_id in lane.get("evidenceInputs", []) or []:
        item = ctx.case_file_items_by_id.get(ev_id)
        if item is None:
            continue
        shape = item.get("shape", {}) or {}
        required_fields = ", ".join(shape.get("required", []) or []) or "—"
        kind = item.get("kind", "—")
        rows.append([ev_id, kind, required_fields])
    if not rows:
        return "## Input Quality Gate\n\nThis lane declares no evidence inputs. Confirm with the process owner before proceeding.\n"
    body = table(["Evidence id", "Kind", "Required fields"], rows)
    return "## Input Quality Gate\n\nBefore acting in this lane, confirm every declared evidence input is present with the required fields.\n\n" + body + "\n"


def _rules(ctx: GeneratorContext, lane: dict[str, Any]) -> str:
    authority = lane.get("authority", {}) or {}
    allowed = authority.get("allowedActions", []) or []
    prohibited = authority.get("prohibitedActions", []) or []

    def _line(action_id: str) -> str:
        entry = ctx.actions_by_id.get(action_id, {})
        label = entry.get("label", action_id)
        definition = " ".join(entry.get("definition", "").split())
        return f"`{action_id}` — **{label}**. {definition}".rstrip()

    allowed_block = bullet_list(_line(a) for a in allowed) if allowed else "_None declared._"
    prohibited_block = bullet_list(_line(a) for a in prohibited) if prohibited else "_None declared._"
    plane = authority.get("plane", "—")
    tier = authority.get("autonomyTier", "—")
    risk = authority.get("riskTier", "—")

    return (
        "## Rules\n\n"
        f"**Authority plane:** `{plane}`  \n"
        f"**Autonomy tier:** `{tier}`  \n"
        f"**Risk tier:** `{risk}`\n\n"
        "### Allowed actions\n\n"
        f"{allowed_block}\n\n"
        "### Prohibited actions\n\n"
        f"{prohibited_block}\n"
    )


def _state_loop(lane: dict[str, Any]) -> str:
    state_model = lane.get("stateModel") or {}
    states = state_model.get("states") or []
    transitions = state_model.get("transitions") or []
    if not states:
        return "## State Loop\n\nThis lane declares no state model. Confirm with the process owner whether a state loop is intentional.\n"

    state_rows = []
    for state in states:
        flags = []
        if state.get("isInitial"):
            flags.append("initial")
        if state.get("isTerminal"):
            flags.append("terminal")
        state_rows.append([state["id"], state.get("label", state["id"]), ", ".join(flags) or "—"])

    transition_rows = []
    for transition in transitions:
        guard = transition.get("guard") or {}
        guard_summary = "—"
        if guard:
            rules = guard.get("rules") or []
            if rules:
                guard_summary = "; ".join((r.get("when") or "") for r in rules)
        transition_rows.append([
            transition.get("id", "—"),
            transition.get("from", "—"),
            transition.get("to", "—"),
            transition.get("gate", "—"),
            guard_summary,
        ])

    states_table = table(["State", "Label", "Flags"], state_rows)
    transitions_table = table(["Transition", "From", "To", "Gate", "Guard rules"], transition_rows) if transition_rows else ""
    chunks = ["## State Loop\n\n### States\n\n" + states_table + "\n"]
    if transitions_table:
        chunks.append("### Transitions\n\n" + transitions_table + "\n")
    return "\n".join(chunks)


def _gates(ctx: GeneratorContext, lane: dict[str, Any]) -> str:
    state_model = lane.get("stateModel") or {}
    transitions = state_model.get("transitions") or []
    lane_gate_ids = {transition.get("gate") for transition in transitions if transition.get("gate")}
    if not lane_gate_ids:
        return "## Gates\n\nThis lane does not own any gates directly. Refer to upstream lanes for approval gates that apply.\n"
    chunks = ["## Gates\n"]
    for gate_id in sorted(g for g in lane_gate_ids if g):
        gate = ctx.gates_by_id.get(gate_id)
        if not gate:
            continue
        chunks.append(_render_gate(gate))
    return "\n".join(chunks)


def _render_gate(gate: dict[str, Any]) -> str:
    decision = gate.get("decision") or {}
    rules = decision.get("rules") or []
    inputs = decision.get("inputs") or []
    else_clause = decision.get("else") or "(none)"
    rule_rows = []
    for rule in rules:
        effect = rule.get("effect") or {}
        effect_parts = []
        if effect.get("transitionTo"):
            effect_parts.append(f"→ `{effect['transitionTo']}`")
        if effect.get("recordEvidence"):
            recorded = ", ".join(effect["recordEvidence"])
            effect_parts.append(f"record: {recorded}")
        rule_rows.append([
            rule.get("when", "—"),
            rule.get("then", "—"),
            "; ".join(effect_parts) or "—",
        ])
    rules_table = table(["When", "Then", "Effect"], rule_rows) if rule_rows else "_No decision rules declared._"
    inputs_block = ", ".join(inputs) if inputs else "—"
    return (
        f"### Gate `{gate['id']}` — {gate.get('label', gate['id'])}\n\n"
        f"**Type:** `{gate.get('gateType', '—')}`  \n"
        f"**Approval role:** `{gate.get('approvalRole', '—')}`  \n"
        f"**Approval condition:** {gate.get('approvalCondition', '—')}  \n"
        f"**Escalation condition:** {gate.get('escalationCondition', '—')}\n\n"
        f"**Decision inputs:** {inputs_block}\n\n"
        f"{rules_table}\n\n"
        f"**Else:** `{else_clause}`\n"
    )


def _evidence_to_produce(ctx: GeneratorContext, lane: dict[str, Any]) -> str:
    outputs = lane.get("evidenceOutputs", []) or []
    if not outputs:
        return "## Evidence To Produce\n\nThis lane declares no evidence outputs. Confirm with the process owner whether the lane should produce any auditable evidence.\n"
    rows: list[list[str]] = []
    for ev_id in outputs:
        item = ctx.case_file_items_by_id.get(ev_id, {})
        shape = item.get("shape", {}) or {}
        required = ", ".join(shape.get("required", []) or []) or "—"
        rows.append([ev_id, item.get("kind", "—"), required, item.get("retentionPolicy", "—")])
    body = table(["Evidence id", "Kind", "Required fields", "Retention"], rows)
    return "## Evidence To Produce\n\nProduce the following evidence before leaving this lane. Use the spec's `evidenceModel.caseFileItems[]` shape exactly.\n\n" + body + "\n"


def _stop_conditions(ctx: GeneratorContext, lane: dict[str, Any]) -> str:
    state_model = lane.get("stateModel") or {}
    terminals = [state for state in state_model.get("states", []) or [] if state.get("isTerminal")]
    transitions = state_model.get("transitions") or []
    items: list[str] = []
    for terminal in terminals:
        items.append(f"Lane reaches terminal state `{terminal['id']}` ({terminal.get('label', '')}).")
    for transition in transitions:
        guard = transition.get("guard") or {}
        if guard.get("else") == "block":
            items.append(f"Transition `{transition.get('id', '')}` from `{transition.get('from', '')}` is guarded; if no rule allows it, the lane stops and escalates.")
    for gate_id, gate in ctx.gates_by_id.items():
        if gate.get("gateType") == "escalating":
            items.append(f"Gate `{gate_id}` is escalating; reaching it pauses the lane until human approval.")
    if not items:
        return "## Stop Conditions\n\nNo automated stop conditions are declared. Escalate any time the lane lacks evidence, scope, or authority.\n"
    return "## Stop Conditions\n\n" + bullet_list(items) + "\n"


def compose_lane_skill(ctx: GeneratorContext, lane: dict[str, Any]) -> tuple[str, str]:
    """Return (skill_id, skill_md_content) for the lane."""
    skill_id = _skill_id(ctx.process_id, lane["id"])
    sections = [
        _front_matter(ctx.process_id, lane, skill_id),
        f"# {ctx.process_name} — {lane.get('label', lane['id'])}\n",
        f"## Purpose\n\n{lane.get('purpose', '').rstrip()}\n",
        _input_quality_gate(ctx, lane),
        _rules(ctx, lane),
        _state_loop(lane),
        _gates(ctx, lane),
        _evidence_to_produce(ctx, lane),
        _stop_conditions(ctx, lane),
        _NON_CLAIM,
    ]
    return skill_id, "\n".join(section.rstrip() + "\n" for section in sections)
