"""Translate a v0.1 ga-process YAML dict into a v1 dict shape."""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any

from .match import fuzzy_action_match


_TERMINAL_HINTS = {
    "closed",
    "done",
    "archived",
    "approved",
    "completed",
    "rejected",
    "abandoned",
    "out_of_scope",
    "not_gadd_work",
    "duplicate",
}


def _slug(text: str) -> str:
    out = []
    for ch in text.lower():
        if ch.isalnum():
            out.append(ch)
        elif out and out[-1] != "-":
            out.append("-")
    return "".join(out).strip("-")


def _underscore_slug(text: str) -> str:
    return _slug(text).replace("-", "_")


def _skill_slug(text: str) -> str:
    return _slug(text)


def _resolve_actions(prose_list: list[str], catalog: list[dict[str, Any]]) -> tuple[list[str], list[dict[str, Any]]]:
    matched: list[str] = []
    unmatched: list[dict[str, Any]] = []
    seen: set[str] = set()
    for prose in prose_list:
        action_id, _score = fuzzy_action_match(prose, catalog)
        if action_id and action_id not in seen:
            matched.append(action_id)
            seen.add(action_id)
            continue
        if action_id:
            continue
        slug = _slug(prose)
        if not slug or slug in seen:
            continue
        unmatched.append({
            "id": slug,
            "label": prose,
            "category": "data-plane-persist",
            "defaultAutonomyTier": "execute_with_approval",
            "defaultRiskTier": "medium",
            "definition": f"TODO: migrated from v0.1 free-text action {prose!r}; review and normalize against the action catalog.",
            "justification": "Auto-generated by migrate-gaps-v0-to-v1; human review required before promoting beyond descriptive conformance.",
        })
        seen.add(slug)
    return matched, unmatched


def _translate_lane(
    lane_id: str,
    lane_data: dict[str, Any],
    catalog: list[dict[str, Any]],
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    authority = lane_data.get("authority", {}) or {}
    allowed, unmatched_allowed = _resolve_actions(authority.get("allowed", []) or [], catalog)
    prohibited, unmatched_prohibited = _resolve_actions(authority.get("prohibited", []) or [], catalog)

    state_model_states = []
    for index, state_name in enumerate(lane_data.get("states", []) or []):
        sid = _underscore_slug(state_name) or f"state_{index}"
        entry = {"id": sid, "label": state_name}
        if index == 0:
            entry["isInitial"] = True
        if index == len(lane_data.get("states", []) or []) - 1:
            entry["isTerminal"] = True
        state_model_states.append(entry)
    state_model = None
    if state_model_states:
        transitions = []
        for index, state in enumerate(state_model_states[:-1]):
            next_state = state_model_states[index + 1]
            transitions.append({
                "id": f"t-{state['id'].replace('_', '-')}-to-{next_state['id'].replace('_', '-')}",
                "from": state["id"],
                "to": next_state["id"],
            })
        state_model = {"states": state_model_states, "transitions": transitions}

    prohibited_set = set(prohibited)
    allowed = [action_id for action_id in allowed if action_id not in prohibited_set]

    lane_v1: dict[str, Any] = {
        "id": lane_id,
        "label": lane_id.replace("_", " ").title(),
        "purpose": lane_data.get("purpose", ""),
        "authority": {
            "plane": authority.get("plane", "data_plane"),
            "autonomyTier": authority.get("autonomyTier", "draft"),
            "riskTier": authority.get("riskTier", "medium"),
            "allowedActions": allowed,
            "prohibitedActions": prohibited,
        },
        "skills": [_skill_slug(skill) for skill in (lane_data.get("skills", []) or []) if _skill_slug(skill)],
    }
    if state_model is not None:
        lane_v1["stateModel"] = state_model
    if lane_data.get("autonomousResponsibilities"):
        resps, _ = _resolve_actions(lane_data["autonomousResponsibilities"], catalog)
        lane_v1["autonomousResponsibilities"] = resps
    return lane_v1, unmatched_allowed + unmatched_prohibited


def _translate_gates(lanes_v0: dict[str, Any]) -> list[dict[str, Any]]:
    gates: list[dict[str, Any]] = []
    for lane_data in lanes_v0.values():
        for gate in lane_data.get("gates", []) or []:
            gid = gate.get("id", _slug(gate.get("approvalCondition", "gate")))
            gates.append({
                "id": gid,
                "label": gate.get("id", gid).replace("_", " ").title(),
                "gateType": gate.get("gateType", "validating"),
                "approvalRole": gate.get("approvalRole", "approver"),
                "approvalCondition": gate.get("approvalCondition", ""),
                "escalationCondition": gate.get("escalationCondition", ""),
            })
    return gates


def _translate_control_mappings(v0: dict[str, Any]) -> dict[str, Any]:
    catalog_refs = [
        "gaps/catalogs/v1/controls/nist-ai-rmf.json",
        "gaps/catalogs/v1/controls/iso-42001-annex-a.json",
        "gaps/catalogs/v1/controls/eu-ai-act-articles.json",
    ]
    implementations: list[dict[str, Any]] = []
    for mapping in v0.get("controlMappings", []) or []:
        status_v0 = mapping.get("implementationStatus", "unreviewed")
        status_v1 = {
            "implemented": "implemented",
            "partial": "partial",
            "planned": "planned",
            "unreviewed": "planned",
            "not_applicable": "not-applicable",
        }.get(status_v0, "planned")
        control_id = str(mapping.get("controlId", "")) or "UNKNOWN"
        source = str(mapping.get("source", ""))
        if control_id == "GOVERN" and "NIST" in source:
            control_id = "GOVERN-1.4"
        elif control_id == "Annex A" and "42001" in source:
            control_id = "A.5.4"
        elif control_id == "Article 26" and "AI Act" in source:
            control_id = "Art.26"
        implementations.append({
            "controlId": control_id,
            "mappingStatus": status_v1,
            "statement": "Migrated from v0.1. Review and refine before declaring machine-validatable conformance.",
        })
    return {
        "catalogRefs": catalog_refs,
        "controlImplementations": implementations,
    }


def _translate_risk_patterns(v0: dict[str, Any]) -> list[dict[str, Any]]:
    patterns_v0 = v0.get("governedAutonomyRiskPatterns", {}) or {}
    rename = {
        "chat_as_control_plane": "chat-as-control-plane",
        "unbounded_delegation": "unbounded-delegation",
        "role_collapse": "role-collapse",
        "evidence_drift": "evidence-drift",
        "approval_theater": "approval-theater",
        "tool_sprawl": "tool-sprawl",
        "accountability_gaps": "accountability-gaps",
        "scope_creep_at_machine_speed": "scope-creep-at-machine-speed",
        "post_hoc_governance": "post-hoc-governance",
    }
    out: list[dict[str, Any]] = []
    for key, body in patterns_v0.items():
        ref = rename.get(key, key.replace("_", "-"))
        mitigation = body.get("mitigation") if isinstance(body, dict) else None
        out.append({
            "patternRef": ref,
            "mitigations": [mitigation] if mitigation else ["Migrated from v0.1; refine before promoting beyond descriptive."],
        })
    return out


def translate(v0: dict[str, Any], action_catalog: list[dict[str, Any]], source_path: Path) -> dict[str, Any]:
    process_v0 = v0.get("process", {}) or {}
    lanes_v0 = v0.get("lanes", {}) or {}

    lanes_v1: list[dict[str, Any]] = []
    extra_local_actions: list[dict[str, Any]] = []
    for lane_id, lane_data in lanes_v0.items():
        lane_v1, unmatched = _translate_lane(lane_id, lane_data, action_catalog)
        lanes_v1.append(lane_v1)
        extra_local_actions.extend(unmatched)

    seen_local: set[str] = set()
    deduped_local: list[dict[str, Any]] = []
    for entry in extra_local_actions:
        if entry["id"] in seen_local:
            continue
        seen_local.add(entry["id"])
        deduped_local.append(entry)

    roles_v1: list[dict[str, Any]] = []
    for role_id, role_data in (v0.get("roles", {}) or {}).items():
        roles_v1.append({
            "id": role_id,
            "label": role_data.get("label", role_id.replace("_", " ").title()),
            "accountabilityScope": f"TODO: migrate accountability scope for {role_id} from v0.1.",
            "decisionRights": [],
        })

    today = _dt.date.today().isoformat()

    v1: dict[str, Any] = {
        "gapsVersion": "1.0.0",
        "specStatus": "draft",
        "conformanceLevel": "descriptive",
        "process": {
            "id": process_v0.get("id", source_path.parent.name),
            "name": process_v0.get("name", source_path.parent.name),
            "purpose": process_v0.get("purpose", ""),
            "scope": {
                "includes": list((process_v0.get("scope", {}) or {}).get("includes", []) or []),
                "excludes": list((process_v0.get("scope", {}) or {}).get("excludes", []) or []),
            },
        },
        "substrate": {
            "oscalControlCatalogs": [
                "gaps/catalogs/v1/controls/nist-ai-rmf.json",
                "gaps/catalogs/v1/controls/iso-42001-annex-a.json",
                "gaps/catalogs/v1/controls/eu-ai-act-articles.json",
            ],
            "actionCatalog": "gaps/catalogs/v1/actions.yml",
            "evidenceCatalog": "gaps/catalogs/v1/evidence-kinds.yml",
            "riskPatternCatalog": "gaps/catalogs/v1/risk-patterns.yml",
        },
        "roles": roles_v1,
        "evidenceModel": {
            "caseFileItems": [
                {
                    "id": "migrated-process-state",
                    "kind": "state-transition-event",
                    "label": "Migrated v0.1 process state placeholder",
                    "producer": "lane:" + (lanes_v1[0]["id"] if lanes_v1 else "unknown"),
                    "consumer": ["role:" + roles_v1[0]["id"]] if roles_v1 else [],
                }
            ],
        },
        "lanes": lanes_v1,
        "gates": _translate_gates(lanes_v0),
        "projectionPolicy": {
            "canonicalStateSource": "repo-local-ledger",
            "pathPattern": (v0.get("canonicalState", {}) or {}).get("pathPattern", "state/**"),
        },
        "riskPatterns": _translate_risk_patterns(v0),
        "controlAssessment": _translate_control_mappings(v0),
        "freshness": {
            "reviewedAt": today,
            "driftPolicy": "Migrated from v0.1. Review and uplift to machine-validatable conformance before relying on this spec.",
        },
        "knownGaps": [
            {
                "id": "migrated-from-v0-1",
                "summary": "Spec was migrated mechanically from v0.1. Many fields are placeholders; uplift before declaring machine-validatable.",
                "severity": "important",
                "plannedResolution": "manual-port-review",
            }
        ],
    }
    if deduped_local:
        v1["process"]["localActions"] = deduped_local
    return v1
