"""Recover a v1 spec representation from a generated skill package."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from gaps_v1_validator.loader import load_yaml  # noqa: E402


class LiftError(Exception):
    pass


def lift_package(package_root: Path) -> dict[str, Any]:
    impl_path = package_root / "implementation.v1.yml"
    if not impl_path.exists():
        raise LiftError(
            f"{package_root}: missing implementation.v1.yml; lift requires a Phase 4 generated package"
        )
    impl = load_yaml(impl_path)
    if impl.get("implementationType") != "agent_skill_package":
        raise LiftError(f"{impl_path}: unsupported implementationType {impl.get('implementationType')!r}")
    if impl.get("generatedBy") != "gaps-v1-generator":
        raise LiftError(
            f"{impl_path}: package was not generated by gaps-v1-generator; manual lift is not supported in v1.0.0"
        )
    return {
        "implementation": impl,
        "lanes": _collect_lane_skills(package_root, impl),
        "fingerprint": (impl.get("implementationFingerprint") or {}).get("value"),
    }


def _collect_lane_skills(package_root: Path, impl: dict[str, Any]) -> list[dict[str, Any]]:
    skill_root = package_root / impl.get("skillsRoot", "skills")
    lanes: list[dict[str, Any]] = []
    for lane_impl in impl.get("laneImplementations", []) or []:
        skill_id = lane_impl["skill"]
        skill_md_path = skill_root / skill_id / "SKILL.md"
        if not skill_md_path.exists():
            continue
        lanes.append(
            {
                "laneId": lane_impl["laneId"],
                "skill": skill_id,
                "skillMd": skill_md_path.read_text(encoding="utf-8"),
                "states": lane_impl.get("states", []) or [],
                "transitions": lane_impl.get("transitions", []) or [],
                "gates": lane_impl.get("gates", []) or [],
                "evidenceInputs": lane_impl.get("evidenceInputs", []) or [],
                "evidenceOutputs": lane_impl.get("evidenceOutputs", []) or [],
            }
        )
    return lanes
